### PR TITLE
Fix getParameter spoofing for WebGLRenderingContext

### PR DESCRIPTION
**Pull request by petr-vysotskiy**
Hey,

We've faced the issue mentioned here:
https://github.com/berstend/puppeteer-extra/issues/33#issuecomment-497033554

So, here is the fix.

### CODE REVIEW

**Comment by berstend** [comment]
@petr-vysotskiy awesome, thanks for the PR! 👍 

Do you know if this breaks any existing behavior or pages or is it safe to merge?
I'm currently in the middle of rewriting the core to TS and can't test this in detail. :)

Thanks a lot!

**Comment by petr-vysotskiy** [comment]
You are welcome. Thanks @berstend for the work you've done, it helped us. We've tested the fix and it works fine with Distil.

**Comment by petr-vysotskiy** [comment]
> But, Distil still detects me as a bot.
Can you see any other errors? Have you used a proxy to make sure your IP isn't blocked by Distil? Which site are you trying to visit using puppeter?

**Comment by kfunk1** [comment]
Unfortunately, I don't see any other error.
I am not using a proxy.
I am always able through a real chrome, so it's not an ip problem.
https://www.axs.com/browse/music

I've tried in headless mode on, it seems to be working.

**Pull request closed without merging**
