### PR TITLE
chore: Replace deprecated waitFor with waitForTimeout

### PR DESCRIPTION
**Pull request by josep11**

### CODE REVIEW

**Comment by Niek** [comment]
This will break support for older Puppeteer versions (where the new function doesn't exist), see https://github.com/berstend/puppeteer-extra/pull/441/checks?check_run_id=2005933640

Can you inject the function in the page object in case it doesn't exist?

**Comment by josep11** [comment]
Hey Niek, I tried to look for where to inject the function and I am not sure if this would be the file to do it:
/packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js

And if the answer is yes, would it go at the begginning of the:
onPageCreated function?

The code would be the following:
```js
if (typeof page.waitForCustom !== "function") {
        page.waitForTimeout = (milliseconds) => {
            return this.mainFrame().waitForTimeout(milliseconds);
        };
}
```

Thanks,

**Comment by berstend** [comment]
We would need to do monkey patch this in the plugin framework for all consumers to have access to it.

As this only affects plugin developers and not many files I wouldn't mind being verbose:
```js
await (async ms => ('waitForTimeout' in page ? page.waitForTimeout(ms) : page.waitFor(ms)))(5 * 1000)
```
or less concise:
```js
if ('waitForTimeout' in page) {
	await page.waitForTimeout(5 * 1000)
} else {
	await page.waitFor(5 * 1000)
}
```

**Comment by berstend** [comment]
Or we just do this in our tests:
```js
page.waitForTimeout = page.waitForTimeout || page.waitFor; // support older pptr versions
await page.waitForTimeout(5 * 1000)
```

**Comment by josep11** [comment]
Hello @berstend I am trying to run the tests locally but I have a library dependency incompatibility on npm install.
What should I do not to mess it up?
--force, or --legacy-peer-deps?


> While resolving: puppeteer-extra-plugin-adblocker@2.11.10
> npm ERR! Found: @types/puppeteer@2.1.5
> npm ERR! node_modules/@types/puppeteer
> npm ERR!   dev @types/puppeteer@"^2.0.0" from puppeteer-extra-plugin-adblocker@2.11.10
> npm ERR!   packages/puppeteer-extra-plugin-adblocker
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @types/puppeteer@"5.x" from @cliqz/adblocker-puppeteer@1.18.8
> npm ERR! node_modules/@cliqz/adblocker-puppeteer
> npm ERR!   @cliqz/adblocker-puppeteer@"^1.18.6" from puppeteer-extra-plugin-adblocker@2.11.10
> npm ERR!   packages/puppeteer-extra-plugin-adblocker

**Comment by josep11** [comment]
So, I added the line you recommended twice in the file:
/packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.test.js

All tests passed in CI, so I think it is ready to merge.



> Or we just do this in our tests:
> 
> ```js
> page.waitForTimeout = page.waitForTimeout || page.waitFor; // support older pptr versions
> await page.waitForTimeout(5 * 1000)
> ```
> 
> edit, yeah let's do that - @josep11 could you do the above in our .js files? Not needed in our .md examples. :-)

**Review by berstend — APPROVED** [review]
LGTM

**Comment by berstend** [comment]
thanks @josep11 👍

**Pull request merged**
