### PR TITLE
Fix #36 for incognito context. 

### LINKED ISSUE #36: Incognito browser context shares the same cookies
When creating an incognito context with puppeteer-extra it shares the same cookies. However, the incognito context works fine with default puppeteer. 

Example server gist: https://gist.github.com/jjason685/20d83ab49bff9a40d1d9d41427145bbd
Example test gist: https://gist.github.com/jjason685/79bf37acba80a2c1f0af4f6c7a1cdf37

Log output: 

No cookie, sending.
Received cookie from instance

Clearly depicting that the cookies are shared.

### PR DESCRIPTION
**Pull request by RusTit**
Fixing closure for `arguments` variable

### CODE REVIEW

**Comment by RusTit** [comment]
Fix #36

**Comment by wokao98** [comment]
good job...thanks

**Comment by johnculviner** [comment]
Can we get this merged. Fixed my issue!

**Comment by berstend** [comment]
@wokao98 @johnculviner @deprecated apologies for the delay, I was occupied with work stuff.

@RusTit great fix, thanks a lot! I updated deps and refactored the code a bit in between so I had to commit the fix in a different commit to keep things simple.

The fix is published as `puppeteer-extra@2.1.6`

**Comment by RusTit** [comment]
@berstend No issues with that, and again, thanks to you for this library.

**Pull request closed without merging**
