### PR TITLE
fix(plugin-stealth): Improve iframe.contentWindow evasion

### PR DESCRIPTION
**Pull request by regseb**
I think I found how Cloudflare detects puppeteer: `iframe.contentWindow[0]` returns `undefined` in Chrome and returns `window` with puppeteer (and _iframe.contentWindow_ evasion). I modify `contentWindowProxy` to returns `undefined`.

Here is a case to see the difference between Chrome and puppeteer (with _iframe.contentWindow_ evasion).

```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script>
        // https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/iframe.contentWindow/index.js
        const contentWindowProxy = {
            get(target, key) {
                // Now to the interesting part:
                // We actually make this thing behave like a regular iframe window,
                // by intercepting calls to e.g. `.self` and redirect it to the correct thing. :)
                // That makes it possible for these assertions to be correct:
                // iframe.contentWindow.self === window.top // must be false
                if (key === 'self') {
                    return this
                }
                // iframe.contentWindow.frameElement === iframe // must be true
                if (key === 'frameElement') {
                    return iframe
                }
                return Reflect.get(target, key)
            }
        }

        const body = document.querySelector('body')
        const iframe = document.createElement('iframe')

        const proxy = new Proxy(window, contentWindowProxy)
        Object.defineProperty(iframe, 'contentWindowStealth', {
            get() {
                return proxy
            },
            set(newValue) {
                return newValue; // contentWindow is immutable
            },
            enumerable: true,
            configurable: false
        })

        iframe.srcdoc = 'foobar'
        console.log("proxy before append iframe", proxy);
        body.appendChild(iframe)
        console.log("proxy after append iframe", proxy);

        console.log("iframe.contentWindow[0]", iframe.contentWindow[0])
        console.log("iframe.contentWindowStealth[0]", iframe.contentWindowStealth[0])
    </script>
  </body>
</html>
```

With this pull request, I no longer have the error indicated in the issue https://github.com/berstend/puppeteer-extra/issues/532#issuecomment-909472096, but puppeteer still can't pass the Cloudflare redirect.

### CODE REVIEW

**Review by kasjp — APPROVED** [review]

**Comment by mfunder** [comment]
@regseb 
This solves the problem for me. Perhaps this pull request would get more attention, and be easier for others to find and apply, if the title included "(CloudFlare fix)"?

**Review by berstend — APPROVED** [review]
Looking good, thanks for adding the tests @regseb 👍

**Comment by berstend** [comment]
```
Successfully published:
 - puppeteer-extra-plugin-stealth@2.7.10
```
thanks @regseb 👍 

cc @pussyslain @mfunder

**Comment by norstbox** [comment]
@mfunder
So, you could pass CloudFlare JS challenge with this patch? Do you use puppeteer in `headless: false` mode?

**Comment by mfunder** [comment]
@norstbox It seems to only work with headful: true.
It also seems that Cloudflare is running several anti-bot scripts, and this patch only helps with one of them. But since Cloudflare uses a different script on each page refresh, and refreshes by itself on failure, it eventually gets through.

**Pull request merged**
