### PR TITLE
Try to fallback to `puppeteer-core` if `puppeteer` is not available

### PR DESCRIPTION
**Pull request by haggholm**
What it says on the label. Maybe not the flexible as it doesn’t make it easier to dropin forks &c., but it’s a quick solution that probably does what *most* people are looking for. Cf. https://github.com/berstend/puppeteer-extra/issues/27

### CODE REVIEW

**Comment by shirshak55** [comment]
Try catch is really not the good way to handle such flow?

**Comment by Kikobeats** [comment]
You in case you are interested, I created a module for that purpose https://github.com/Kikobeats/require-one-of 😂

**Comment by berstend** [comment]
@haggholm apologies for the delay and thanks for contributing :) I'm currently refactoring the core to TS and will make sure to use your fix if it still seems like the best way in the new setup.

**Comment by berstend** [comment]
Fix for the time being:

> according to ["puppeteer vs puppeteer-core"](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core) [](/GoogleChrome/puppeteer/blob/HEAD@{2019-09-29T16:37:13Z}/docs/api.md#puppeteer-vs-puppeteer-core) they have two main differences...
> 
> > To sum up, the only differences between puppeteer-core and puppeteer are:
> > 
> > * puppeteer-core doesn't automatically download Chromium when installed.
> > * puppeteer-core ignores all PUPPETEER_* env variables.
> 
> You can avoid downloading chrome using the [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#environment-variables) [](/GoogleChrome/puppeteer/blob/HEAD@{2019-09-29T16:37:13Z}/docs/api.md#environment-variables) environment variable during installation. This makes `puppeteer` almost identical to `puppeteer-core` with the added benefit of convenient env vars.
> 
> e.g. `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm install puppeteer`

I'm closing this PR for now but keep this in mind when I refactor the core to TypeScript and will also update the docs. :)

**Comment by berstend** [comment]
`v3.1.3` will now attempt to require `puppeteer-core` as well :)

**Comment by elyas-bhy** [comment]
@berstend is this documented anywhere?

**Pull request closed without merging**
