### PR TITLE
Added puppeteer-extra-plugin-minmax to README

### PR DESCRIPTION
**Pull request by Stillerman**

### CODE REVIEW

**Comment by brunogaspar** [comment]
Not sure if we should add a list of plugins from the community to separate from the official ones.

What you think @berstend ?

**Comment by berstend** [comment]
Hmm, I favor adding the plugins under a community headline, so it's clear they're not under the control of the main project. :-)

But nice to see new plugins being developed, thanks @Stillerman

I have some time tomorrow and will update the PR with a respective change.

**Comment by moltar** [comment]
Agree with @berstend we should have a separate section with the community ones.

**Comment by berstend** [comment]
Uhm, given how cumbersome it still is to modify PRs from other people I'm gonna merge this in (so Stillerman gets attribution) and modify the readme afterwards. :-)

**Comment by berstend** [comment]
Here's the commit with the updated Community Plugin section: https://github.com/berstend/puppeteer-extra/commit/32e2eb442af4ed1df3768d462638371fffecb80c

**Pull request merged**
