### PR TITLE
fix(plugin-user-data-dir): Use rimraf to delete temp userDataDir

### PR DESCRIPTION
**Pull request by thibaultmthh**
Fixes: #581, #601

The current solution was failing sometimes to delete the directory because some files were still used by chrome. 
Also this issue was causing the process to freeze

Ex : 
`
Error: EPERM: operation not permitted, unlink 'C:\Users\Moi\AppData\Local\Temp\puppeteer_dev_profile-KKPhhn\BrowserMetrics\BrowserMetrics-62B2BDF7-4CE8.pma
`

Using rimraf allows better error logging and does not freeze the process.

Link to discord discussion https://discord.com/channels/737009125862408274/737010839172939898/988781077885763614

### CODE REVIEW

**Comment by thibaultmthh** [comment]
I also changed the test workflow so we can start it manually without creating a pull request

**Comment by berstend** [comment]
```
Successfully published:
 - extract-stealth-evasions@2.7.0
 - puppeteer-extra-plugin-stealth@2.11.0
 - puppeteer-extra-plugin-user-data-dir@2.4.0
 - puppeteer-extra-plugin-user-preferences@2.4.0
```
thanks @thibaultmthh 👍

**Comment by zebn** [comment]
Still have this issue with rimraf when running multiple instances of puppeteer, and can't catch it with browser.close().catch:

`
"extract-stealth-evasions": "^2.7.0",
    "puppeteer-extra-plugin-stealth": "^2.11.0",
    "puppeteer-extra-plugin-user-data-dir": "^2.4.0",
    "puppeteer-extra-plugin-user-preferences": "^2.4.0",
    "puppeteer-extra": "3.3.4"`


`AssertionError [ERR_ASSERTION]: rimraf: missing path
    at rimraf (/root/pbot-lin/node_modules/rimraf/rimraf.js:54:3)
    at Plugin.deleteUserDataDir (/root/pbot-lin/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:71:5)
    at Plugin.onDisconnected (/root/pbot-lin/node_modules/puppeteer-extra-plugin-user-data-dir/index.js:118:12)
    at /root/pbot-lin/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:68
    at Array.map (<anonymous>)
    at Object.emit (/root/pbot-lin/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Browser.emit (/root/pbot-lin/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /root/pbot-lin/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:141:25
    at /root/pbot-lin/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:68
    at Array.map (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}`

**Comment by berstend** [comment]
@zebn are you using `addExtra` as mentioned in the readme?

**Comment by antfuentes87** [comment]
> @zebn are you using `addExtra` as mentioned in the readme? Otherwise you're using the same puppeteer instance which can cause problems

I am tried using `addExtra` and got the same issue with `rimraf`. Is there anything else you have to do? I am trying to run 20+ puppeteers at the same time using express.js

**Pull request merged**
