### PR TITLE
fix(plugin-recaptcha): Update hCaptcha Detection

### PR DESCRIPTION
**Pull request by spyfly**
Fix berstend/puppeteer-extra#472

### CODE REVIEW

**Comment by berstend** [comment]
@spyfly thanks, LGTM 👍 

Our CI is choking on something unrelated, looking into that

**Comment by spyfly** [comment]
> @spyfly thanks, LGTM 👍 
> 
> Our CI is choking on something unrelated, looking into that 

@berstend I've also fixed `@extra/recaptcha` in the automation-extra branch, want me to open a PR for that aswell?

**Comment by berstend** [comment]
> @berstend I've also fixed `@extra/recaptcha` in the automation-extra branch, want me to open a PR for that aswell?

That'd be great 😍 thanks!

**Comment by berstend** [comment]
```
Successfully published:
 - puppeteer-extra-plugin-recaptcha@3.3.8
```
thanks @spyfly 👍

**Pull request merged**
