### PR TITLE
Update index.js for bypass creepjs proxy detection

### PR DESCRIPTION
**Pull request by cg10036**
Update index.js for bypass creepjs proxy detection

### CODE REVIEW

**Comment by berstend** [comment]
@cg10036 thanks! does this have negative side effects elsewhere?

**Comment by cg10036** [comment]
@berstend Yep! This code just change stack trace, so it will have no negative effets maybe.

```
// before bypass
TypeError: Function.prototype.toString requires that 'this' be a Function
    at Function.toString (<anonymous>)
    at newHandler.<computed> [as apply] (eval at <anonymous> (:4:65), <anonymous>:18:30)
    at newHandler.<computed> [as apply] (eval at <anonymous> (:4:65), <anonymous>:18:30)
    at newHandler.<computed> [as apply] (eval at <anonymous> (:4:65), <anonymous>:18:30)
    at newHandler.<computed> [as apply] (eval at <anonymous> (:4:65), <anonymous>:18:30)
```
```
// after bypass
TypeError: Function.prototype.toString requires that 'this' be a Function
    at Function.toString (<anonymous>)
    at you (https://abrahamjuliot.github.io/creepjs/creep.js:1685:50)
    at cant (https://abrahamjuliot.github.io/creepjs/creep.js:1686:24)
    at hide (https://abrahamjuliot.github.io/creepjs/creep.js:1687:24)
    at getNewObjectToStringTypeErrorLie (https://abrahamjuliot.github.io/creepjs/creep.js:1688:5)
    at https://abrahamjuliot.github.io/creepjs/creep.js:5622:8
    at getHeadlessFeatures (https://abrahamjuliot.github.io/creepjs/creep.js:5633:8)
    at async Promise.all (index 0)
    at async fingerprint (https://abrahamjuliot.github.io/creepjs/creep.js:11412:8)
    at async https://abrahamjuliot.github.io/creepjs/creep.js:11690:7
```

**Comment by berstend** [comment]
I like it 😄 quite an elegant solution 👍

**Comment by berstend** [comment]
Will merge it in & release it after the weekend, currently having some Github CI issues

**Review by meodemsao — APPROVED** [review]

**Comment by Bllacky** [comment]
Can we please merge this ?

**Comment by mikeyfarina** [comment]
@berstend Can we merge this?

**Comment by sagistrauss** [comment]
Doesn't seem to work anymore.

**Comment by philipnimble** [comment]
This does not seem to work anymore - does anybody know of another walkaround to this issue? 
maybe @cg10036 ?

**Comment by cg10036** [comment]
Does not work anymore, closing pr

**Pull request closed without merging**
