### PR TITLE
Launch options merge fixed

### PR DESCRIPTION
**Pull request by zdm**
Removed deepmerge when merging options in launch() method.

### CODE REVIEW

**Comment by itsdarrylnorris** [comment]
Hey @zdm ,

If I am not wrong [this PR](https://github.com/berstend/puppeteer-extra/pull/268) solves this issue. We are have considering moving to object-merge-advanced with isPlainObject.

Do you know if this will fix your problem?

**Comment by zdm** [comment]
Hey.
No, my issue is related to launch method only, where merge is not 
required at all and can be avoided.

**Comment by zdm** [comment]
The test `options/will modify puppeteer launch options through plugins` is not passed even on original code.

Could somebody merge this PR pls?

**Comment by berstend** [comment]
What's the benefit of this, performance?

This will be gone in the rewrite (#313) anyway: https://github.com/berstend/puppeteer-extra/pull/303/files#diff-204794cd3a2e9247e20d8a1f99cc73c8R75-R91

**Comment by berstend** [comment]
Closing in favor of #268

**Pull request closed without merging**
