### PR TITLE
fix(plugin-stealth): Properly delete webdriver, fixes #222

### LINKED ISSUE #222: navigator.webdriver still can be detected
```
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())

puppeteer.launch({ headless: true }).then(async browser => {
    const page = await browser.newPage()
    page.on('console', msg => console.log(msg.text()))
    await page.goto('https://bot.sannysoft.com')
    await page.evaluate(async () => {
        console.log('webdriver' in navigator ? 'detected': 'not detected')
        console.log(navigator.webdriver === undefined ? 'not detected': 'detected')
        // but!
        console.log(Object.getOwnPropertyDescriptor(navigator.__proto__, 'webdriver') === undefined ? 'not detected': 'detected once')
        for (let prop in navigator) {
            if (prop === 'webdriver') {
                console.log('detected twice')
            }
        }
    });

    await browser.close()
})
```

```
const newProto = navigator.__proto__;
delete newProto.webdriver;
navigator.__proto__ = newProto
```
was more correct way to remove `webdriver` from `navigator`.

### PR DESCRIPTION
**Pull request by Niek**

### CODE REVIEW

**Comment by aabbccsmith** [comment]
What does this bring that the current solution doesn't offer?

**Comment by Niek** [comment]
See #222, the current approach can be detected.

**Comment by Niek** [comment]
Added some extra tests that show the issues with the current implementatin.

**Comment by berstend** [comment]
> Added some extra tests that show the issues with the current implementation.

Great 👍

**Comment by berstend** [comment]
Published as `puppeteer-extra-plugin-stealth@2.4.13`

**Pull request merged**
