### PR TITLE
Add improved navigator.webdriver evasion

### PR DESCRIPTION
**Pull request by aabbccsmith**
Now works with very advanced instanceof test.

### CODE REVIEW

**Comment by Niek** [comment]
To fix the failing test, run ``eslint --fix --ext .js .``

**Comment by berstend** [comment]
I'll merge in the PR soon and do that locally (will also add tests). I'm being slowed down a bit by TravisCI 😅

**Comment by berstend** [comment]
image

**Comment by aabbccsmith** [comment]
Woop! Glad I could help.

**Comment by berstend** [comment]
Released in `puppeteer-extra-plugin-stealth@2.4.7`. :) Thanks a lot!

**Comment by Niek** [comment]
I did some testing and noticed an issue with this code - function calls on the navigator object no longer work. For example, Google Analytics calls ``navigator.javaEnabled()`` and this throws the error ``Uncaught TypeError: Illegal invocation``.

**Comment by aabbccsmith** [comment]
Amazing! @Niek

**Comment by berstend** [comment]
@Niek's fix has been release as `puppeteer-extra-plugin-stealth@2.4.9`.

**Comment by aabbccsmith** [comment]
Fantastic!

**Comment by morlockaerospace** [comment]
> instanceof test

Is there an example of this instanceof test? I cannot find a reference to it.

**Pull request merged**
