### PR TITLE
upgrade code to support puppeteer 8.0.0

### PR DESCRIPTION
**Pull request by UrielCh**
puppeteer 8.0.0 is writen in typescript, so we do not need @types/puppeteer

puppeteer use some typescript v4+ feature, I upgrade typescript version to the same as puppeteer  currently use.

do you realy want to keep retrocompatibility with old puppeteer ?

if to the gitflow must be change. (multiple option are posible here)

I tryed to made as little change as possible.

@cliqz/adblocker-puppeteer must be upgrade to 1.20.+
typescript must be 4+, ^4.1.5 is currently use in puppeter source.

let me know you point.

### CODE REVIEW

**Comment by berstend** [comment]
Unfortunately the situation is a bit more complex, the built-in types are still not as good as the `@types/puppeteer` ones.

Please see this for more context: https://github.com/berstend/puppeteer-extra/issues/428#issuecomment-778679665

> do you realy want to keep retrocompatibility with old puppeteer ?

yes :-)

**Comment by berstend** [comment]
I wonder if there's a way to use the built-in types if available and fallback to `@types/puppeteer` if not. The biggest issue here is that our own code needs types and they're unfortunately different.

**Comment by UrielCh** [comment]
let try this matrix:
```
   puppeteer_version:
          - 8.0.0 # Chromium 90.0.4427.0, Feb 18, 2021
          - 7.0.0 # Chromium 90.0.4403.0, Feb 3, 2021
          # - 5.0.0 # Chromium 83.0.4103.0, Jul 2, 2020
          - 2.1.1 # Chromium 79.0.3942.0, Oct 24 2019
          # - 2.0.0 # Chromium 79.0.3942.0, Oct 24 2019
          # - 1.20.0 # Chromium 78.0.3882.0, Sep 13 2019
          # - 1.15.0 # Chromium 75.0.3765.0, Apr 26 2019
          # - 1.9.0 # Chromium 71.0.3563.0, Oct 4, 2018
          # - 1.6.2 # Chromium 69.0.3494.0, Aug 1, 2018
```

**Comment by UrielCh** [comment]
this one will fail, let me find a solution ....

**Comment by UrielCh** [comment]
The workflow tests randomly fail.

but all test are Okey.

It's need more Github workflow ressources, let remove pptr 7.0

**Comment by UrielCh** [comment]
so github workflows can not support more than 4 build.

**Comment by UrielCh** [comment]
:tada:

**Comment by UrielCh** [comment]
Now pptr 8.0.0 is installed by default, workflow, will downgrade pptr for testing.

**Comment by berstend** [comment]
@UrielCh I found a way to support both old and new puppeteer types: #555

Your PR was a nice reference 👍

**Comment by berstend** [comment]
Closing this PR now, given #555 has been published. Thanks!

**Pull request closed without merging**
