### PR TITLE
update user-agent version regex extraction

### PR DESCRIPTION
**Pull request by nguyen930411**
Hello guys,
It needs to update to match some new chrome user-agents, example one: 
`Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36`

### CODE REVIEW

**Comment by berstend** [comment]
@nguyen930411 thanks for the interest in contributing! could you add some tests with old/new chrome user agents?

**Comment by nguyen930411** [comment]
Hi @berstend,
Sorry for the late response, I've added the test please check it.
This is also my first PR so if there is something wrong please help me fix it 👀 .
Thanks.

**Comment by berstend** [comment]
Why did this PR became so messed up with all the other commits showing here 🤔 

@nguyen930411 I was hoping the tests would make it clearer what the purpose of this PR is but I still don't understand why the updated regex is needed or what it does better?

**Comment by nguyen930411** [comment]
@berstend Honestly, I have no idea why there are so many other commit around this PR too 😢  .
I'm not good at git command, I followed this post to update my forked repo: 
https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository
If this PR is really too messed up to merged, you could close this PR then just help me update the new regex to the master branch.

About the regex, you can try this code to reproduce the problem:
```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
puppeteer.use(StealthPlugin());

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        args: [
            '--user-agent=Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36',
        ]
    });
    await browser.newPage();
    await browser.close();
})();
```

And this is the error show up:

```
(node:18584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at _getPlatformVersion (C:\Projects\BOT\puppeteer\node_modules\puppeteer-extra-plugin-stealth\evasions\user-agent-override\index.js:139:49)
    at Plugin.onPageCreated (C:\Projects\BOT\puppeteer\node_modules\puppeteer-extra-plugin-stealth\evasions\user-agent-override\index.js:161:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin._onTargetCreated (C:\Projects\BOT\puppeteer\node_modules\puppeteer-extra-plugin\dist\index.cjs.js:494:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by berstend** [comment]
Thanks for the PR! Closing in favor of #563

**Pull request closed without merging**
