### PR TITLE
feat(plugin-stealth): Rewrite window.chrome evasions

### LINKED ISSUE #218: Tiktok is detecting puppeteer-extra-plugin-stealth
Hi everyone,

I'm curently working on a tiktok scraper, using the stealth plugin from the begining of it, but today when i'm trying to go on a tiktok profile i'm getting this:

Capture d’écran 2020-06-05 à 13 00 01

Any Idea how to fix it ? 

For the code i'm using (code for testing the connection):

```
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
var fs = require("fs");

(async () => {
    try {
      puppeteer.use(StealthPlugin())
      var browser = await puppeteer.launch({
          headless: false,
        });
      var page = await browser.newPage();
      await page.goto(`https://www.tiktok.com/@miss_extra2.0`);
      await page.waitFor(50000)
      await browser.close();
    } catch (err) {
      await browser.close();
    }
  })();

```

### PR DESCRIPTION
**Pull request by berstend**
Our current `window.chrome` mocks are pretty unconvincing, I've used the new [utility functions](https://github.com/berstend/puppeteer-extra/pull/291) to create much better (and functional!) ones.

Due to increased complexity I've split the single `chrome.runtime` evasion up in multiple `chrome.` evasions.

Also introduces the concept of using `utils.cache` for cached copies of e.g. `Reflect.get`, so the site cannot overload these functions to sniff usage within our JS Proxies.

Fixes #218

### Currently implemented
- [x]  `chrome.runtime`
- [x]  `chrome.runtime.sendMessage`
- [x]  `chrome.runtime.connect`
- [x] `chrome.csi`
- [x] `chrome.loadTimes`
- [x] `chrome.app`

### CODE REVIEW

**Comment by berstend** [comment]
That felt like a rabbit hole but `chrome.runtime` is now complete 😄

**Comment by berstend** [comment]
All done! Apologies for this massive PR, but it made sense to do all the `window.chrome` stuff in one step.

**Comment by Niek** [comment]
Excellent work 👏🏻

**Comment by berstend** [comment]
Published in `puppeteer-extra-plugin-stealth@2.6.0`

**Pull request merged**
