### PR TITLE
feat(plugin-stealth): Mask vendor in WebGL2RenderingContext

### PR DESCRIPTION
**Pull request by berstend**
Imagine my surprise when I happened to land on [this site](https://browserleaks.com/webgl) and to notice that there's another WebGL context named `WebGL2RenderingContext` (which this site uses to determine the vendor). 😅 

Sorry for not adding additional tests, I'm a bit short on time and the existing ones cover the evasion logic already.

### CODE REVIEW

**Comment by berstend** [comment]
Just noticed this was mentioned here as well: https://github.com/berstend/puppeteer-extra/issues/239#issuecomment-654527015

**Comment by berstend** [comment]
Also my initial 2 second attempt to use a loop for brevity weren't successful here :-)

**Comment by Niek** [comment]
Can't this be abstracted as ``[WebGLRenderingContext, WebGL2RenderingContext].forEach((gl) => { ... });`` ?

**Comment by berstend** [comment]
Super weird, but this won't patch it correctly and makes the tests fail (also the version without `.prototype`):

```
        ;[
          (WebGLRenderingContext.prototype, WebGL2RenderingContext.prototype)
        ].forEach(contextProto => {
          Object.defineProperty(contextProto, 'getParameter', {
            configurable: true,
            enumerable: false,
            writable: false,
            value: new Proxy(
              contextProto.getParameter,
              getParameterProxyHandler
            )
          })
        })
```

Gonna look at this more closely over the weekend.

**Comment by berstend** [comment]
@Niek The person how makes this work with a loop get's a free beer from me 😄 
There's something weird going on with `Object.defineProperty` that makes it impossible. I still made it more terse and added extra tests for good measure - I think it's fine to be merged now.

**Comment by berstend** [comment]
I'm gonna merge this in now and we shall never speak of `Object.defineProperty` in loops. :-)

**Comment by Niek** [comment]
It looks great now :)

**Comment by berstend** [comment]
Published as `puppeteer-extra-plugin-stealth@2.5.0`

**Pull request merged**
